// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/proto/stream_logs.proto

package streamlogs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamLogs_StreamLogEntries_FullMethodName = "/streamlogs.StreamLogs/StreamLogEntries"
)

// StreamLogsClient is the client API for StreamLogs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamLogsClient interface {
	StreamLogEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogEntry, LogControl], error)
}

type streamLogsClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamLogsClient(cc grpc.ClientConnInterface) StreamLogsClient {
	return &streamLogsClient{cc}
}

func (c *streamLogsClient) StreamLogEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogEntry, LogControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamLogs_ServiceDesc.Streams[0], StreamLogs_StreamLogEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, LogControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamLogs_StreamLogEntriesClient = grpc.BidiStreamingClient[LogEntry, LogControl]

// StreamLogsServer is the server API for StreamLogs service.
// All implementations must embed UnimplementedStreamLogsServer
// for forward compatibility.
type StreamLogsServer interface {
	StreamLogEntries(grpc.BidiStreamingServer[LogEntry, LogControl]) error
	mustEmbedUnimplementedStreamLogsServer()
}

// UnimplementedStreamLogsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamLogsServer struct{}

func (UnimplementedStreamLogsServer) StreamLogEntries(grpc.BidiStreamingServer[LogEntry, LogControl]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogEntries not implemented")
}
func (UnimplementedStreamLogsServer) mustEmbedUnimplementedStreamLogsServer() {}
func (UnimplementedStreamLogsServer) testEmbeddedByValue()                    {}

// UnsafeStreamLogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamLogsServer will
// result in compilation errors.
type UnsafeStreamLogsServer interface {
	mustEmbedUnimplementedStreamLogsServer()
}

func RegisterStreamLogsServer(s grpc.ServiceRegistrar, srv StreamLogsServer) {
	// If the following call pancis, it indicates UnimplementedStreamLogsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamLogs_ServiceDesc, srv)
}

func _StreamLogs_StreamLogEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamLogsServer).StreamLogEntries(&grpc.GenericServerStream[LogEntry, LogControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamLogs_StreamLogEntriesServer = grpc.BidiStreamingServer[LogEntry, LogControl]

// StreamLogs_ServiceDesc is the grpc.ServiceDesc for StreamLogs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamLogs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamlogs.StreamLogs",
	HandlerType: (*StreamLogsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogEntries",
			Handler:       _StreamLogs_StreamLogEntries_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/stream_logs.proto",
}
