// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/stream_logs.proto

package streamlogs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogControl_Command int32

const (
	LogControl_NONE          LogControl_Command = 0 // no-op
	LogControl_PAUSE         LogControl_Command = 1 // pause sending logs
	LogControl_RESUME        LogControl_Command = 2 // resume sending logs
	LogControl_CHANGE_FILTER LogControl_Command = 3 // change filter criteria
)

// Enum value maps for LogControl_Command.
var (
	LogControl_Command_name = map[int32]string{
		0: "NONE",
		1: "PAUSE",
		2: "RESUME",
		3: "CHANGE_FILTER",
	}
	LogControl_Command_value = map[string]int32{
		"NONE":          0,
		"PAUSE":         1,
		"RESUME":        2,
		"CHANGE_FILTER": 3,
	}
)

func (x LogControl_Command) Enum() *LogControl_Command {
	p := new(LogControl_Command)
	*p = x
	return p
}

func (x LogControl_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogControl_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_stream_logs_proto_enumTypes[0].Descriptor()
}

func (LogControl_Command) Type() protoreflect.EnumType {
	return &file_api_proto_stream_logs_proto_enumTypes[0]
}

func (x LogControl_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogControl_Command.Descriptor instead.
func (LogControl_Command) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_stream_logs_proto_rawDescGZIP(), []int{1, 0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_stream_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stream_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_stream_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       LogControl_Command     `protobuf:"varint,1,opt,name=command,proto3,enum=streamlogs.LogControl_Command" json:"command,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // optional human-readable info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogControl) Reset() {
	*x = LogControl{}
	mi := &file_api_proto_stream_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogControl) ProtoMessage() {}

func (x *LogControl) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stream_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogControl.ProtoReflect.Descriptor instead.
func (*LogControl) Descriptor() ([]byte, []int) {
	return file_api_proto_stream_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogControl) GetCommand() LogControl_Command {
	if x != nil {
		return x.Command
	}
	return LogControl_NONE
}

func (x *LogControl) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_stream_logs_proto protoreflect.FileDescriptor

const file_api_proto_stream_logs_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/stream_logs.proto\x12\n" +
	"streamlogs\"X\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9f\x01\n" +
	"\n" +
	"LogControl\x128\n" +
	"\acommand\x18\x01 \x01(\x0e2\x1e.streamlogs.LogControl.CommandR\acommand\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\aCommand\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02\x12\x11\n" +
	"\rCHANGE_FILTER\x10\x032R\n" +
	"\n" +
	"StreamLogs\x12D\n" +
	"\x10StreamLogEntries\x12\x14.streamlogs.LogEntry\x1a\x16.streamlogs.LogControl(\x010\x01B1Z/golang-services/api/proto/streamlogs;streamlogsb\x06proto3"

var (
	file_api_proto_stream_logs_proto_rawDescOnce sync.Once
	file_api_proto_stream_logs_proto_rawDescData []byte
)

func file_api_proto_stream_logs_proto_rawDescGZIP() []byte {
	file_api_proto_stream_logs_proto_rawDescOnce.Do(func() {
		file_api_proto_stream_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_stream_logs_proto_rawDesc), len(file_api_proto_stream_logs_proto_rawDesc)))
	})
	return file_api_proto_stream_logs_proto_rawDescData
}

var file_api_proto_stream_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_stream_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_stream_logs_proto_goTypes = []any{
	(LogControl_Command)(0), // 0: streamlogs.LogControl.Command
	(*LogEntry)(nil),        // 1: streamlogs.LogEntry
	(*LogControl)(nil),      // 2: streamlogs.LogControl
}
var file_api_proto_stream_logs_proto_depIdxs = []int32{
	0, // 0: streamlogs.LogControl.command:type_name -> streamlogs.LogControl.Command
	1, // 1: streamlogs.StreamLogs.StreamLogEntries:input_type -> streamlogs.LogEntry
	2, // 2: streamlogs.StreamLogs.StreamLogEntries:output_type -> streamlogs.LogControl
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_stream_logs_proto_init() }
func file_api_proto_stream_logs_proto_init() {
	if File_api_proto_stream_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_stream_logs_proto_rawDesc), len(file_api_proto_stream_logs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_stream_logs_proto_goTypes,
		DependencyIndexes: file_api_proto_stream_logs_proto_depIdxs,
		EnumInfos:         file_api_proto_stream_logs_proto_enumTypes,
		MessageInfos:      file_api_proto_stream_logs_proto_msgTypes,
	}.Build()
	File_api_proto_stream_logs_proto = out.File
	file_api_proto_stream_logs_proto_goTypes = nil
	file_api_proto_stream_logs_proto_depIdxs = nil
}
