root = "."
tmp_dir = "tmp"

[build]
  # IMPORTANT: Change the cmd path for each service
  cmd = "go build -o ./tmp/main ./cmd/ingestion-service"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  log = "air_errors.log"

[log]
  time = true